steps:
  # Build Docker image for pos
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${_PROJECT_ID}/posimage:latest",
        "-f",
        "deployment/Dockerfile-pos",
        ".",
      ]

  # Build Docker image for database
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${_PROJECT_ID}/databaseimage:latest",
        "-f",
        "deployment/Dockerfile-database",
        ".",
      ]

  # Push Docker images to container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/posimage:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_PROJECT_ID}/databaseimage:latest"]

  # Apply Kubernetes deployment file to POS3 cluster
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "deployment.yml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-south1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=pos3"
      - "CLOUDSDK_CORE_PROJECT=${_PROJECT_ID}"

substitutions:
  _PROJECT_ID: app-mod-gebu-trainees
